modLoader="javafml"
loaderVersion="[28,)" # Forge version
issueTrackerURL="https://github.com/svenhjol/Strange/issues"
displayURL="https://svenhjol.github.io/Strange/"
#logoFile="examplemod.png"
#credits="Credits"

[[mods]]
modId="strange"
version="${version}" #mandatory
displayName="Strange"
description='''
Charm, but Stranger.
'''
authors="svenhjol"

[[dependencies.strange]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.1.118,)" #mandatory
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER

[[dependencies.strange]]
    modId="charm" #mandatory
    mandatory=true #mandatory
    versionRange="[1.14.4-1.5,)" #mandatory
    ordering="AFTER" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER